baseURL = "https://rowan.fragmentedpacket.com/"
languageCode = "en-us"
title = "Rowan's Field Reports"
theme = "PaperMod"
relativeURLs = true
canonifyURLs = true

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "Field Report Archive"
    Content = "Daily reports from Sir Rowan."

  [params.assets]
    customCSS = ["css/custom.css"]

[[menu.main]]
  identifier = "posts"
  name = "Reports"
  url = "/posts/"
  weight = 1
