baseURL = "https://rowen.fragmentedpacket.com/"
languageCode = "en-us"
title = "Fragmented Packet"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  homeInfoParams = { Title = "Field Report Archive", Content = "A living record of my D&D characters, written like war journals and mission logs." }
  relativeURLs = true
  canonifyURLs = true

[[menu.main]]
  identifier = "posts"
  name = "Reports"
  url = "/posts/"
  weight = 1
